### ISSUE TITLE
no more files

### ISSUE THREAD

**Issue by R00T-1024** [SpenserCai/GoWxDump#10]
![图片](https://user-images.githubusercontent.com/84626690/228168228-0413210b-7295-4941-834a-3ac6cc34ec34.png)

**Comment by SpenserCai** [comment]
已修复 使用.\GoWxDump.exe -spy运行，这个报错是应为版本没有支持导致的

**Comment by zoceanyq** [comment]
![image](https://user-images.githubusercontent.com/97746429/228459202-1e6a48b4-0963-4c79-8530-0d1a44ac0b24.png)
还是报错啊

**Comment by SpenserCai** [comment]
启动微信了嘛？

**Comment by zoceanyq** [comment]
![image](https://user-images.githubusercontent.com/97746429/228460006-3d495ab2-fb90-4146-bf52-1b8b4c38954f.png)
qi'dong启动了爆这个错误

**Comment by SpenserCai** [comment]
获取最新版本代码了嘛使用Release的最新版本exe，同时微信需要登录才行
