### ISSUE TITLE
可否在 Release 中提供编译好的版本方便使用？这里编译了一个当前最新版本。

### ISSUE THREAD

**Issue by yxzlwz** [SpenserCai/GoWxDump#13]
可否在 Release 中提供编译好的版本方便使用？这里编译了一个当前最新版本。

[GoWxDump.zip](https://github.com/SpenserCai/GoWxDump/files/11182406/GoWxDump.zip)

**Comment by SpenserCai** [comment]
已经提供了源码的Release里就是最新的版本哈
