### ISSUE TITLE
GoWxDump.exe打开秒闪退怎么解决哇

### ISSUE THREAD

**Issue by Neroisbest** [SpenserCai/GoWxDump#14]

**Comment by SpenserCai** [comment]
在命令行执行GoWxDump.exe -spy，确保运行的时候微信打开并且登录

**Comment by Neroisbest** [comment]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.GetWeChatInfo()
        C:/Users/Administrator/Desktop/GoWxDump-master/cmd_action.go:19 +0x469
main.main()
        C:/Users/Administrator/Desktop/GoWxDump-master/main.go:62 +0x57f

**Comment by Neroisbest** [comment]
cmd运行报错 大佬帮忙看看这个怎么解决呢

**Comment by Neroisbest** [comment]
啊 解决了 升级微信版本更新就好 谢谢大佬

**Comment by Neroisbest** [comment]
我想问 解密后怎么看消息 db文件好乱

**Comment by SpenserCai** [comment]
可以下载一个navicat Premium拖进去就好了

**Comment by Neroisbest** [comment]
我想问的是 聊天消息是存在哪个db文件里 好像打开看消息都不全 最近的聊天消息都没找到

**Comment by Neroisbest** [comment]
博主 我发现不同设备同一账号的key会变 那以前保存的msg就完全没有办法解密了吗

**Comment by SpenserCai** [comment]
MSG0.db这种就是了再里面的MSG表里，如果消息多了会有MSG1.db、MSG2.db这种库可以理解成分库不分表

**Comment by Neroisbest** [comment]
请问一下 这个key会变 那以前保存的msg也就不能用现在key 我是不是能这样操作 把微信文档里的msg（或者只替换Multi下msg0.db）全部替换成旧的保存的msg 然后打开微信登陆一次 旧的msg.db的key就会变成新的

**Comment by SpenserCai** [comment]
key一般只有换了系统才会变

**Comment by 774649283** [comment]
> GoWxDump.exe -spy

我这边也是，出现这个报错，我已经是最新的微信了，不知道怎么解决

**Comment by SpenserCai** [comment]
.26的版本还没更新

**Comment by yeyi913** [comment]
> .26的版本还没更新

PS C:\Users\ASUS> cd
PS C:\Users\ASUS> cd E:\Go语言微信取证工具GoWxDump-1.0.12
PS E:\Go语言微信取证工具GoWxDump-1.0.12> cd E:\Go语言微信取证工具GoWxDump-1.0.12\GoWxDump-1.0.12\Release
PS E:\Go语言微信取证工具GoWxDump-1.0.12\GoWxDump-1.0.12\Release> GoWxDump.exe -spy
GoWxDump.exe : 无法将“GoWxDump.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径
，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ GoWxDump.exe -spy
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (GoWxDump.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: 找不到命令 GoWxDump.exe，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载命令。如果信任此命令，请改为键入“.\GoWxDump.exe”。有关详细信息，请参阅 "get-help about_Command_Precedence"。
PS E:\Go语言微信取证工具GoWxDump-1.0.12\GoWxDump-1.0.12\Release> .\GoWxDump.exe -spy
GetWeChatWinModule error:  Only part of a ReadProcessMemory or WriteProcessMemory request was completed.我是报这个错
