### ISSUE TITLE
关于微信目录的问题

### ISSUE THREAD

**Issue by test-git111** [SpenserCai/GoWxDump#4]
如果之前更改过微信文件的保存目录，解密微信数据库时，程序会报下面的错
<img width="855" alt="1" src="https://user-images.githubusercontent.com/78329083/222997844-93d8af0b-1e02-4335-9520-5e96b1f49fdc.png">
导致这个问题的原因是更改微信文件保存目录后，C盘的C:\Users\[User]\Documents\WeChat Files目录不会自动删除，GoWxDump识别到存在此目录，就会解密相关文件，但是此目录下并没有微信相关的文件了。

删除C盘的微信目录后就可以手动选择目录
<img width="584" alt="2" src="https://user-images.githubusercontent.com/78329083/222999110-9b8abe3d-8ef8-4aee-8c4f-573cb02ad49b.png">

建议作者判断一下，如果微信目录不存在相关文件就提示更改目录，或自动搜索全盘微信目录

**Comment by SpenserCai** [comment]
好的，自己修改该过微信目录的这个没有考虑到，手动选择目录限制在了列出的范围，这个我修改该以下，支持手动输入微信目录

**Comment by SpenserCai** [comment]
已修复，如果无法自动识别，列出id和目录，目录在列表里的输入id即可，不在的输入完整路径 @test-git111

**Comment by SpenserCai** [comment]
已修复，关闭issue
