### ISSUE TITLE
微信消息目录问题

### ISSUE THREAD

**Issue by ayjin-dev** [SpenserCai/GoWxDump#5]
运行GoWxDump.exe后如何手动指定微信消息目录问题？

**Comment by SpenserCai** [comment]
最新的这个版本是会提示输入的

**Comment by SpenserCai** [comment]
GoWxDump.exe -spy
在运行到解密的时候会提示从列表中选一个目录（输入[]里面的id），如果没有列出来手动输入完整的目录

**Comment by ayjin-dev** [comment]
> GoWxDump.exe -spy 在运行到解密的时候会提示从列表中选一个目录（输入[]里面的id），如果没有列出来手动输入完整的目录
![tp](https://user-images.githubusercontent.com/51260176/223343684-14f7c2bf-1d19-4ab0-90e4-a38f5f71abf0.png)
这是我的运行结果，并没有提示输入窗口

**Comment by ayjin-dev** [comment]
我的微信目录是自己设定的，可能是这个原因它扫描不出来。这种情况我该如何手动指定呢？

**Comment by SpenserCai** [comment]
你这个情况应该是完全找不到目录，所以没有列出来，我修复一下这种情况

**Comment by shangdev** [comment]
@SpenserCai 好像没修复？
![image](https://user-images.githubusercontent.com/15621520/226233282-9584da6a-2aee-4838-8ec1-21db3df769d4.png)

**Comment by SpenserCai** [comment]
直接使用-spy试试看

**Comment by shangdev** [comment]
@SpenserCai 是这样子吗
![image](https://user-images.githubusercontent.com/15621520/226245416-54878a77-fc6b-441b-98e9-fb28717880d6.png)

**Comment by bsll0828** [comment]
对于多开很多个微信的情况, 能否同时手动指定消息目录和解密key;

**Comment by SpenserCai** [comment]
来Discord群吧感觉好像有点不太一样啊哈哈，可以尝试从Release里下载最新的版本，如果还是有问题来discord群
