### ISSUE TITLE
微信名称乱码

### ISSUE THREAD

**Issue by wind226** [SpenserCai/GoWxDump#7]
![image](https://user-images.githubusercontent.com/24953996/223414835-b8d273a5-50a8-46fa-be45-06c71a6d25af.png)

**Comment by SpenserCai** [comment]
是否存在多个微信账号，我这边发现多个微信账号是存在这个问题的

**Comment by wind226** [comment]
> 是不存在多个微信账号，我这边发现多个微信账号存在这个问题的

我本地只有一个微信号，我的微信名称是6个汉字，我刚刚改成数字名称就获取到了，还有个问题就是cmd_action.go的		dataDirName, err := GetWeChatData(WeChatDataObject.WeChatHandle, WeChatDataObject.WeChatWinModel.ModBaseAddr+uintptr(OffSetMap[WeChatDataObject.Version][5]), 100)
它好像获取不到内容了

**Comment by SpenserCai** [comment]
我觉得这有可能是编码的问题导致汉字异常，我回头测试以下，然后dataDirName的这个貌似是偏移不太固定，所以加了手动选择目录。

**Comment by SpenserCai** [comment]
在 [V1.0.8](https://github.com/SpenserCai/GoWxDump/releases/tag/v1.0.8) 中修复了中文昵称无法读取的bug

**Comment by wind226** [comment]
> 在 [V1.0.8](https://github.com/SpenserCai/GoWxDump/releases/tag/v1.0.8) 中修复了中文昵称无法读取的bug

![image](https://user-images.githubusercontent.com/24953996/223622313-81aed39b-34b0-436a-9f24-750d384d8ff3.png)
奇了怪，我的不知道啥情况，还是乱码

**Comment by SpenserCai** [comment]
找到问题了，这个非常奇怪要打开一个微信聊天的窗口才行

**Comment by SpenserCai** [comment]
> 

我理解上这个只有打开聊天窗口的时候才会把NickName写入到这个内存地址

**Comment by wind226** [comment]
> 我觉得这有可能是编码的问题导致汉字异常，我回头测试以下，然后dataDirName的这个貌似是偏移不太固定，所以加了手动选择目录。

这个我有个想法，就是能不能在内存里面找该微信调用的那个文件目录（用户文件目录名称按wxid区分的嘛）的偏移值，我也不咋懂这个，只是想能不能这样搞

**Comment by wind226** [comment]
> > 
> 
> 我理解上这个只有打开聊天窗口的时候才会把NickName写入到这个内存地

> 

我这有个参考项目：https://github.com/x1hy9/WeChatUserDB 通过pymem进行内存数据查找，获取基址+偏移量与特征,从而达到微信版本每次更新不需要重新查找地址

**Comment by SpenserCai** [comment]
> > > 
> > 
> > 
> > 我理解上这个只有打开聊天窗口的时候才会把NickName写入到这个内存地
> 
> > 
> 
> 我这有个参考项目：https://github.com/x1hy9/WeChatUserDB 通过pymem进行内存数据查找，获取基址+偏移量与特征,从而达到微信版本每次更新不需要重新查找地址

好的，这个可以作为一个feature，回头翻译成go，如果打开一个人聊天，能获取到名字的话这个issue我就先关闭啦。
你的这个提议，可以新建一个issue保持打开

**Comment by SpenserCai** [comment]
> > 我觉得这有可能是编码的问题导致汉字异常，我回头测试以下，然后dataDirName的这个貌似是偏移不太固定，所以加了手动选择目录。
> 
> 这个我有个想法，就是能不能在内存里面找该微信调用的那个文件目录（用户文件目录名称按wxid区分的嘛）的偏移值，我也不咋懂这个，只是想能不能这样搞

我也这么想过但是，他貌似没有保存在内存里，我估计是保存在注册表，可以开个issue记录这个问题哈

**Comment by wind226** [comment]
> 我这有个参考项目：https://github.com/x1hy9/WeChatUserDB 通过pymem进行内存数据查找，获取基址+偏移量与特征,从而达到微信版本每次更新不需要重新查找地址

有交流群莫，这交流不太方便捏

**Comment by SpenserCai** [comment]
> > 我这有个参考项目：https://github.com/x1hy9/WeChatUserDB 通过pymem进行内存数据查找，获取基址+偏移量与特征,从而达到微信版本每次更新不需要重新查找地址
> 
> 
> 
> 有交流群莫，这交流不太方便捏

目前没有我可以开个discord哈哈
